# -*- coding: utf-8 -*-
"""Strings&Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qyZOWJCRSYx9VvfT_Os4UL4Wfz7Ckte2

Count vowels in a string.
"""

word = "ajkelihoiyu"
vowels="aeiou"
count = 0
for i in word:
    if i in vowels:
        count +=1
print(count)

""" Count consonants in a string"""

word2="aaabxyzstvw"
consonants = "bcdfghjklmnpqrstvwxyz"
count = 0
for i in word2:
    if i in consonants:
        count +=1
print(count)

"""Reverse a string."""

text = "hello"

reverse = text[::-1]

print(reverse)

"""Check if a string is a palindrome."""

word = input("Enter a word: ").lower()

if word == word[::-1]:
    print("Palindrome")
else:
    print("Not Palindrome")

"""Count words in a sentence."""

wordCount = "I am learning Python"
print(len(wordCount.split()))

""" Count characters (excluding spaces)."""

sentence = "I am learning Python"

words = sentence.split()
text_without_spaces = "".join(words)

print(len(text_without_spaces))

""" Find the largest digit in a number

"""

number = 192345

number_str = str(number)

largest_digit = number_str[0]

for digit in number_str:
    if digit > largest_digit:
        largest_digit = digit

print(int(largest_digit))

"""Find the smallest digit in a number."""

number = 1923450

number_str = str(number)

smallest_digit = number_str[0]

for digit in number_str:
    if digit < smallest_digit:
        smallest_digit = digit

print(int(smallest_digit))

"""Calculate the factorial of a number."""

fact=int(input("Enter "))
result=1
for i in range(1,fact+1):
    result *= i
print(result)

"""Print the multiplication table of a number."""

def multiplication(number):
    for multiplier in range(1, 11):
        product = number * multiplier
        print(product)

multiplication(10)

"""Print all even numbers from 1 to N.

"""

def even_numbers(n):
    for i in range(2, n + 1, 2):
        print(i)

even_numbers(20)

"""Print all odd numbers from 1 to N

"""

def odd_numbers(n):
    for i in range(1, n + 1, 2):
        print(i)

odd_numbers(20)

"""Find the sum of numbers from 1 to N."""

def sum_of_number(n):
  total=0
  for i in range(1,n+1):
   total=total+i
  return total
print(sum_of_number(10))

"""Find the sum of even numbers from 1 to N."""

def sum_of_even(n):
  total=0
  for i in range(2, n + 1, 2):
    total = total + i
  return total
print(sum_of_even(10))

"""Find the sum of odd numbers from 1 to N."""

def sum_of_odd(n):
  total=0
  for i in range(1, n + 1, 2):
    total = total + i
  return total
print(sum_of_odd(10))

"""Check if a number is prime."""

def checkPrime(number):
    if number <= 1:
      print("Not Prime")
      return

    for i in range(2, number):
        if number % i == 0:
            print("Not Prime")
            return

    print("Prime")
checkPrime(2)

""" Print all prime numbers from 1 to N."""

N = int(input("Enter N: "))

for num in range(2, N + 1):
    is_prime = True
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            is_prime = False
            break
    if is_prime:
        print(num, end=" ")

""" Generate the Fibonacci sequence."""

def generateFibonacci(n):
    first = 0
    second = 1

    while first <= n:
        print(first)
        next_number = first + second
        first = second
        second = next_number

generateFibonacci(10)

"""Find the GCD of two numbers."""

first_number = int(input("Enter first number: "))
second_number = int(input("Enter second number: "))

while second_number != 0:
    remainder = first_number % second_number
    first_number = second_number
    second_number = remainder

print("GCD is:", first_number)

""" Find the LCM of two numbers."""

first_number = int(input("Enter first number: "))
second_number = int(input("Enter second number: "))

a = first_number
b = second_number

while b != 0:
    remainder = a % b
    a = b
    b = remainder

gcd = a

lcm = (first_number * second_number)

print("LCM is:", lcm)